/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.consumer.manager;

import business.enterprise.ConsumerEnterprise;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.Organization;
import business.organization.consumer.ConsumerManagerOrganization;
import business.role.Role;
import business.userAccount.UserAccount;
import business.util.request.RequestStatus;
import business.workQueue.ShortageWorkRequest;
import business.workQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Arpit
 */
public class ConsumerManagerRaiseShortageRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegionRequestJPanel
     */
    private JPanel mainPanel;
    private ConsumerEnterprise enterprise;
    private UserAccount account;
    private Network network;
    private boolean hasShortage = false;

    public ConsumerManagerRaiseShortageRequestJPanel(JPanel mainPanel, UserAccount account, ConsumerEnterprise enterprise, Network network) {
        initComponents();
        this.mainPanel = mainPanel;
        this.enterprise = enterprise;
        this.account = account;
        this.network = network;
        populateEmployeeDropDown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblEmployee = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        cmbEmployee = new javax.swing.JComboBox();
        btnRaise = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHeader.setText("NGO Manager - Shortage Request");

        lblEmployee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEmployee.setText("<HTML>Select <br/>Employee:</HTML>");

        lblMessage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMessage.setText("Message:");

        txtMessage.setColumns(20);
        txtMessage.setRows(5);
        jScrollPane.setViewportView(txtMessage);

        btnBack.setText("<<BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRaise.setText("Raise Request");
        btnRaise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaiseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(lblEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane)
                            .addComponent(cmbEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(btnRaise))
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(lblHeader)))
                .addContainerGap(498, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBack, btnRaise});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(lblHeader)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMessage)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnRaise)
                .addGap(47, 47, 47)
                .addComponent(btnBack)
                .addContainerGap(481, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBack, btnRaise, cmbEmployee});

    }// </editor-fold>//GEN-END:initComponents
    public void populateEmployeeDropDown() {
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccount user : organization.getUserAccountDirectory().getUserAccountList()) {
                if (user.getRole().getRoleType().getValue().equals(Role.RoleType.ConsumerWorker.getValue())) {
                    cmbEmployee.addItem(user);
                }
            }
        }
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        mainPanel.remove(this);
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.previous(mainPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRaiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaiseActionPerformed
        // TODO add your handling code here:
        if (txtMessage.getText() == "" || txtMessage.getText() == null) {
            JOptionPane.showMessageDialog(null, "Please enter a message");
            return;
        }
        if (cmbEmployee.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Please select an employee to assign the request to");
            return;
        }
        for (WorkRequest wr : account.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof ShortageWorkRequest) {
                ShortageWorkRequest sr = (ShortageWorkRequest) wr;
                if (sr.getStatus().equals(RequestStatus.getShortageStatusMessage(1))) {
                    hasShortage = true;
                    break;
                }
            }
        }
        if (hasShortage == false) {
            ShortageWorkRequest swr = new ShortageWorkRequest();
            swr.setSender(account);
            swr.setMessage(txtMessage.getText());
            swr.setStatus(RequestStatus.getShortageStatusMessage(1));
            swr.setConsumerName(enterprise.getName());
            swr.setAssignToEmployee((UserAccount) cmbEmployee.getSelectedItem());

            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (!e.getName().equals(enterprise.getName())) {
                    for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                        if (o instanceof ConsumerManagerOrganization) {
                            o.getWorkQueue().getWorkRequestList().add(swr);
                        }
                    }
                }
            }

            JOptionPane.showMessageDialog(null, "Shortage request sucessfully raised");
            account.getWorkQueue().getWorkRequestList().add(swr);
            txtMessage.setText("");

        } else {
            JOptionPane.showMessageDialog(null, "Already sent a request");
            txtMessage.setText("");
            return;
        }

    }//GEN-LAST:event_btnRaiseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRaise;
    private javax.swing.JComboBox cmbEmployee;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTextArea txtMessage;
    // End of variables declaration//GEN-END:variables
}
