/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.logistics.manager;

import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.Organization;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author rebeccabiju
 */
public class LogisticsManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LogisticsManagerWorkAreaJPanel
     */
    private JPanel mainPanel;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private Network network;

    public LogisticsManagerWorkAreaJPanel(JPanel mainPanel, UserAccount account, Organization organization, Enterprise enterprise, Network network) {
        initComponents();
        this.mainPanel = mainPanel;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        lblNameVal.setText(account.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblNameVal = new javax.swing.JLabel();
        btnRestaurantRequest = new javax.swing.JButton();
        btnInvoices = new javax.swing.JButton();
        btnWorkLog = new javax.swing.JButton();
        btnPayementInfo = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(1400, 1000));

        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHeader.setText("Logistics Manager Work Area");

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setText("Welcome: ");

        lblNameVal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNameVal.setText("<<View Name>>");

        btnRestaurantRequest.setBackground(new java.awt.Color(0, 0, 51));
        btnRestaurantRequest.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRestaurantRequest.setForeground(new java.awt.Color(204, 204, 204));
        btnRestaurantRequest.setText("View Work Requests");
        btnRestaurantRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurantRequestActionPerformed(evt);
            }
        });

        btnInvoices.setBackground(new java.awt.Color(0, 0, 51));
        btnInvoices.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInvoices.setForeground(new java.awt.Color(204, 204, 204));
        btnInvoices.setText("Generate Invoices");
        btnInvoices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoicesActionPerformed(evt);
            }
        });

        btnWorkLog.setBackground(new java.awt.Color(0, 0, 51));
        btnWorkLog.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnWorkLog.setForeground(new java.awt.Color(204, 204, 204));
        btnWorkLog.setText("View Work Log");
        btnWorkLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkLogActionPerformed(evt);
            }
        });

        btnPayementInfo.setBackground(new java.awt.Color(0, 0, 51));
        btnPayementInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPayementInfo.setForeground(new java.awt.Color(204, 204, 204));
        btnPayementInfo.setText("View Payment Info");
        btnPayementInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayementInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(478, 478, 478)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnWorkLog, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRestaurantRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInvoices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPayementInfo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNameVal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(494, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnInvoices, btnPayementInfo, btnRestaurantRequest, btnWorkLog});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(lblHeader)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(lblNameVal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestaurantRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInvoices))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWorkLog)
                    .addComponent(btnPayementInfo))
                .addContainerGap(503, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnInvoices, btnPayementInfo, btnRestaurantRequest, btnWorkLog});

    }// </editor-fold>//GEN-END:initComponents

    private void btnRestaurantRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurantRequestActionPerformed
        // TODO add your handling code here:
        LogisticsManagerViewRequestsJPanel logisticsManagerViewRequestsJPanel = new LogisticsManagerViewRequestsJPanel(mainPanel, account, organization, enterprise);
        mainPanel.add("LogisticsManagerViewRequestsJPanel", logisticsManagerViewRequestsJPanel);
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.next(mainPanel);
    }//GEN-LAST:event_btnRestaurantRequestActionPerformed

    private void btnInvoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoicesActionPerformed
        LogisticsManagerGenerateInvoicesJPanel logisticsManagerGenerateInvoicesJPanel = new LogisticsManagerGenerateInvoicesJPanel(mainPanel, account, network);
        mainPanel.add("LogisticsManagerGenerateInvoicesJPanel", logisticsManagerGenerateInvoicesJPanel);
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.next(mainPanel);
    }//GEN-LAST:event_btnInvoicesActionPerformed

    private void btnWorkLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkLogActionPerformed
        // TODO add your handling code here:
        LogisticsManagerViewWorkLogJPanel logisticsManagerViewWorkLogJPanel = new LogisticsManagerViewWorkLogJPanel(mainPanel, enterprise);
        mainPanel.add("LogisticsManagerViewWorkLogJPanel", logisticsManagerViewWorkLogJPanel);
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.next(mainPanel);
    }//GEN-LAST:event_btnWorkLogActionPerformed

    private void btnPayementInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayementInfoActionPerformed
        // TODO add your handling code here:
        LogisticsManagerViewChartJPanel logisticsManagerViewChartJPanel = new LogisticsManagerViewChartJPanel(mainPanel, account);
        mainPanel.add("LogisticsManagerViewChartJPanel", logisticsManagerViewChartJPanel);
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.next(mainPanel);
    }//GEN-LAST:event_btnPayementInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInvoices;
    private javax.swing.JButton btnPayementInfo;
    private javax.swing.JButton btnRestaurantRequest;
    private javax.swing.JButton btnWorkLog;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameVal;
    // End of variables declaration//GEN-END:variables
}
