/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface.supervision.manager;

import business.enterprise.ConsumerEnterprise;
import business.enterprise.Enterprise;
import business.enterprise.SupplierEnterprise;
import business.network.Network;
import business.organization.Organization;
import business.organization.consumer.ConsumerManagerOrganization;
import business.role.Role;
import business.userAccount.UserAccount;
import business.util.inventory.Distributed;
import business.util.item.ItemQuantity;
import business.util.request.RequestItem;
import business.workQueue.CollectionWorkRequest;
import business.workQueue.PaymentWorkRequest;
import business.workQueue.WorkRequest;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Set;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFFont;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Arpit
 */
public class SupervisionManager extends javax.swing.JPanel {

    /**
     * Creates new form SupervisorAdmin
     */
    private JPanel mainPanel;
    private Network network;

    public SupervisionManager(JPanel mainPanel, UserAccount account, Network network) {
        initComponents();
        this.mainPanel = mainPanel;
        this.network = network;
        lblValue.setText(lblValue.getText() + " " + account.getEmployee().getName());
        
        //Customer Reached
        populateReachedChart();
        
        //Product Status
        populateRestaurantCombo();
        populateData(null);
        
        //Chart
        populateChart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnDetails = new javax.swing.JButton();
        lblTotalWastage = new javax.swing.JLabel();
        lblWastageValue = new javax.swing.JLabel();
        btnExport = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        lblRestaurant = new javax.swing.JLabel();
        cmbRestaurant = new javax.swing.JComboBox();
        jScrollPane = new javax.swing.JScrollPane();
        tblWastageAvoided = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblHeader1 = new javax.swing.JLabel();
        pnlChartFed = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pnlChart = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1000, 1000));

        btnDetails.setText("View Details");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        lblTotalWastage.setText("Total Avoided:");

        lblWastageValue.setText("<wastage>");

        btnExport.setText("Export Data");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHeading.setText("Manager Work Area - View");

        lblRestaurant.setText("Supplier");

        cmbRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRestaurantActionPerformed(evt);
            }
        });

        tblWastageAvoided.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier Name", "Wastage Avoided(in pounds)", "Status", "Consumer delivered to"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(tblWastageAvoided);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTotalWastage, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblWastageValue, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblHeading)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRestaurant)
                    .addComponent(cmbRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalWastage)
                    .addComponent(lblWastageValue))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetails)
                    .addComponent(btnExport))
                .addGap(110, 110, 110))
        );

        jTabbedPane1.addTab("Products Status (Tabular)", jPanel1);

        lblHeader1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHeader1.setText("Manager Work Area - Poeple reached Chart");

        pnlChartFed.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlChartFed, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblHeader1)
                .addGap(48, 48, 48)
                .addComponent(pnlChartFed, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Customer Reached", jPanel2);

        pnlChart.setBackground(new java.awt.Color(204, 204, 255));
        pnlChart.setLayout(new java.awt.BorderLayout());

        lblHeader.setBackground(new java.awt.Color(204, 204, 255));
        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHeader.setText("Manager Work Area - Wastage Avoided Chart");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(pnlChart, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblHeader)))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblHeader)
                .addGap(18, 18, 18)
                .addComponent(pnlChart, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addGap(71, 71, 71))
        );

        jTabbedPane1.addTab("Chart", jPanel3);

        lblValue.setText("Welcome, ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(lblValue, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(lblValue)
                .addGap(41, 41, 41)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblWastageAvoided.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null,
                "Please select a request item to view details",
                "Warning",
                JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            CollectionWorkRequest request = (CollectionWorkRequest) tblWastageAvoided.getValueAt(selectedRow, 2);

            SupervisionViewDetails supervisionViewDetails = new SupervisionViewDetails(mainPanel, request);
            mainPanel.add("SupervisionViewDetails", supervisionViewDetails);

            CardLayout layout = (CardLayout) mainPanel.getLayout();
            layout.next(mainPanel);
        }
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblWastageAvoided.getModel();
        XSSFWorkbook workbook = new XSSFWorkbook();
        XSSFSheet worksheet = workbook.createSheet();

        TreeMap<String, Object[]> dataMap = new TreeMap<>();
        dataMap.put("0", new Object[]{
            dtm.getColumnName(0), dtm.getColumnName(1), dtm.getColumnName(2), dtm.getColumnName(3)
        });

        for (int i = 0; i < dtm.getRowCount(); i++) {
            dataMap.put(i + 1 + "", new Object[]{
                dtm.getValueAt(i, 0).toString(),
                dtm.getValueAt(i, 1).toString(),
                dtm.getValueAt(i, 2).toString(),
                dtm.getValueAt(i, 3).toString()
            });
        }

        Set<String> ids = dataMap.keySet();
        XSSFRow row;
        int rowId = 0;

        XSSFCellStyle style = workbook.createCellStyle();
        XSSFFont font = workbook.createFont();
        font.setBoldweight(XSSFFont.BOLDWEIGHT_BOLD);
        style.setFont(font);

        for (String key : ids) {
            row = worksheet.createRow(rowId++);

            Object[] values = dataMap.get(key);

            int cellId = 0;
            for (Object o : values) {
                Cell cell = row.createCell(cellId++);
                cell.setCellValue((String) o);
                if (rowId== 1) {
                    cell.setCellStyle(style);
                }
            }
        }

        try {
            String date = new SimpleDateFormat("MM_dd_yyyy_HH_mm_ss").format(new Date());
            String fileName = "Mayor_" + network.getName() + "_" + date + ".xlsx";
            FileOutputStream fos = new FileOutputStream(new File(System.getProperty("user.home") + "/Desktop/"+fileName));
            workbook.write(fos);
            fos.close();
            JOptionPane.showMessageDialog(null, "Data exported to excel");
        } catch (FileNotFoundException fnfe) {
            // File Not Found
        } catch (IOException iex) {
            // IO Exception block
        }
    }//GEN-LAST:event_btnExportActionPerformed

    private void cmbRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRestaurantActionPerformed
        // TODO add your handling code here:
        if (cmbRestaurant.getSelectedIndex() < 1) {
            populateData(null);
        } else {
            SupplierEnterprise e = (SupplierEnterprise) cmbRestaurant.getSelectedItem();
            populateData(e);
        }
    }//GEN-LAST:event_cmbRestaurantActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnExport;
    private javax.swing.JComboBox cmbRestaurant;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHeader1;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblRestaurant;
    private javax.swing.JLabel lblTotalWastage;
    private javax.swing.JLabel lblValue;
    private javax.swing.JLabel lblWastageValue;
    private javax.swing.JPanel pnlChart;
    private javax.swing.JPanel pnlChartFed;
    private javax.swing.JTable tblWastageAvoided;
    // End of variables declaration//GEN-END:variables

    public void populateReachedChart() {

        DefaultCategoryDataset dataSet = new DefaultCategoryDataset();
        int peopleFed = 0;
        double amount = 0;
        double avoided = 0;
        double wastage = 0;

        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (e.getEnterpriseType() == Enterprise.EnterpriseType.Consumer) {
                String name = e.getName();

                ConsumerEnterprise ne = (ConsumerEnterprise) e;

                //Wastage Avoided
                for (RequestItem ri : ne.getInventory().getRequestItemList()) {
                    avoided += ItemQuantity.getQuantity(ri.getItemName()) * ri.getQuantity();
                }

                // Wastage
                for (RequestItem ri : ne.getWasteInventory().getRequestItemList()) {
                    wastage += ItemQuantity.getQuantity(ri.getItemName()) * ri.getQuantity();
                }

                // People fed
                for (Distributed d : ne.getDistributedList()) {
                    peopleFed += d.getPeopleFed();
                }

                // Expenses
                for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                    if (o instanceof ConsumerManagerOrganization) {
                        for (UserAccount ua : o.getUserAccountDirectory().getUserAccountList()) {
                            for (WorkRequest wr : o.getWorkQueue().getWorkRequestList()) {
                                if (wr instanceof PaymentWorkRequest) {
                                    PaymentWorkRequest pwr = (PaymentWorkRequest) wr;
                                    amount += pwr.getCollectionWorkRequest().getDeliveryCost();
                                }
                            }
                        }
                    }
                }

                dataSet.setValue(avoided, name, "Wastage Avoided ");
                dataSet.setValue(wastage, name, "Wastage in inventory ");
                dataSet.setValue(peopleFed, name, "People Reached");
                dataSet.setValue(amount, name, "Expenses Inccured (in $)");

                peopleFed = 0;
                avoided = 0;
                wastage = 0;
                amount = 0;
            }
        }
        JFreeChart chart = ChartFactory.createBarChart("Analysis report for Consumer",
                "Consumer",
                "Values",
                dataSet,
                PlotOrientation.VERTICAL, true, true, false);

        CategoryPlot plot = chart.getCategoryPlot();

        plot.setRangeGridlinePaint(Color.BLACK);
        plot.setBackgroundPaint(Color.WHITE);

        ChartPanel chartPanel = new ChartPanel(chart);
        pnlChartFed.removeAll();
        pnlChartFed.add(chartPanel, BorderLayout.CENTER);
        pnlChartFed.validate();

    }
    
    public void populateRestaurantCombo() {
        cmbRestaurant.removeAllItems();
        cmbRestaurant.addItem(null);
        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (e.getEnterpriseType() == Enterprise.EnterpriseType.Supplier) {
                cmbRestaurant.addItem(e);
            }
        }
    }

    public void populateData(SupplierEnterprise supplier) {

        DefaultTableModel dtm = (DefaultTableModel) tblWastageAvoided.getModel();
        dtm.setRowCount(0);

        double wastage = 0;

        // All data
        if (supplier == null) {

            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (e.getEnterpriseType() == Enterprise.EnterpriseType.Supplier) {
                    for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                        for (UserAccount ua : o.getUserAccountDirectory().getUserAccountList()) {
                            if ((ua.getRole().getRoleType().getValue()).equals(Role.RoleType.SupplierWorker.getValue())) {
                                for (WorkRequest wr : ua.getWorkQueue().getWorkRequestList()) {
                                    if (wr instanceof CollectionWorkRequest) {
                                        CollectionWorkRequest cwr = (CollectionWorkRequest) wr;

                                        Object row[] = new Object[4];
                                        row[0] = cwr.getRaisedBySupplier();
                                        row[1] = cwr.getTotalQuantity();
                                        row[2] = cwr;
                                        row[3] = cwr.getDeliverToConsumer() == null ? "Undelivered" : cwr.getDeliverToConsumer();
                                        dtm.addRow(row);

                                        wastage += cwr.getTotalQuantity();
                                    }
                                }
                            }
                        }
                    }
                }
            }

        } // Filtered
        else {

            for (Organization o : supplier.getOrganizationDirectory().getOrganizationList()) {
                for (UserAccount ua : o.getUserAccountDirectory().getUserAccountList()) {
                    if ((ua.getRole().getRoleType().getValue()).equals(Role.RoleType.SupplierWorker.getValue())) {
                        for (WorkRequest wr : ua.getWorkQueue().getWorkRequestList()) {
                            CollectionWorkRequest cwr = (CollectionWorkRequest) wr;

                            Object row[] = new Object[4];
                            row[0] = cwr.getRaisedBySupplier();
                            row[1] = cwr.getTotalQuantity();
                            row[2] = cwr;
                            row[3] = cwr.getDeliverToConsumer()== null ? "Undelivered" : cwr.getDeliverToConsumer();
                            dtm.addRow(row);

                            wastage += cwr.getTotalQuantity();
                        }
                    }
                }
            }

        }

        lblWastageValue.setText(wastage + " pounds");
    }
    
    //Chart
    public void populateChart() {

        DefaultCategoryDataset dataSet = new DefaultCategoryDataset();
        double wastageAvoided = 0;

        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (e.getEnterpriseType() == Enterprise.EnterpriseType.Supplier) {
                String name = e.getName();
                for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                    for (UserAccount ua : o.getUserAccountDirectory().getUserAccountList()) {
                        if ((ua.getRole().getRoleType().getValue()).equals(Role.RoleType.SupplierWorker.getValue())) {
                            for (WorkRequest wr : ua.getWorkQueue().getWorkRequestList()) {
                                if (wr instanceof CollectionWorkRequest) {
                                    CollectionWorkRequest cwr = (CollectionWorkRequest) wr;
                                    wastageAvoided += cwr.getTotalQuantity();
                                }
                            }
                        }
                    }
                    dataSet.setValue(wastageAvoided, "Wastage Avoided", name);
                    wastageAvoided = 0;
                }
            }
        }

        JFreeChart chart = ChartFactory.createBarChart("Wastage Avoided by each Supplier",
                "Supplier",
                "Wastage Avoided (In Pounds)",
                dataSet,
                PlotOrientation.VERTICAL, true, true, false);

        CategoryPlot plot = chart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.BLACK);
        plot.setBackgroundPaint(Color.WHITE);

        ChartPanel chartPanel = new ChartPanel(chart);
        pnlChart.removeAll();
        pnlChart.add(chartPanel, BorderLayout.CENTER);
        pnlChart.validate();

    }

}
