/*
 * SupervisionAdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */
package userInterface.supervision.manager;

import business.network.Network;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author swarag
 */
public class SupervisionManagerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel mainPanel;
    private Network network;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public SupervisionManagerWorkAreaJPanel(JPanel mainPanel, UserAccount account, Network network) {
        initComponents();
        this.mainPanel = mainPanel;
        this.network = network;
        lblValue.setText(lblValue.getText() + " " + account.getEmployee().getName());

    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        btnWastageAvoided = new javax.swing.JButton();
        btnPeopleFed = new javax.swing.JButton();
        btnWastageAvoidedChart = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(1400, 1000));

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHeading.setText("Mayor Work Area");

        lblValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValue.setText("Welcome, ");

        btnWastageAvoided.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnWastageAvoided.setText("View Wastage Avoided by Restaurants(Tabular)");
        btnWastageAvoided.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWastageAvoidedActionPerformed(evt);
            }
        });

        btnPeopleFed.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPeopleFed.setText("View People Fed by NGOs");
        btnPeopleFed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeopleFedActionPerformed(evt);
            }
        });

        btnWastageAvoidedChart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnWastageAvoidedChart.setText("View Wastage Avoided by Restaurant(Chart)");
        btnWastageAvoidedChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWastageAvoidedChartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValue, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnWastageAvoided)
                        .addGap(2, 2, 2)
                        .addComponent(btnWastageAvoidedChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPeopleFed, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(407, 407, 407)))
                .addGap(103, 103, 103))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnPeopleFed, btnWastageAvoidedChart});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(lblHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValue)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWastageAvoided, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWastageAvoidedChart, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPeopleFed, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(665, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnPeopleFed, btnWastageAvoided, btnWastageAvoidedChart});

    }// </editor-fold>//GEN-END:initComponents

    private void btnPeopleFedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeopleFedActionPerformed

        SupervisionManagerViewConsumerDataJPanel supervisionManagerViewPeopleFedJPanel = new SupervisionManagerViewConsumerDataJPanel(mainPanel, network);
        mainPanel.add("SupervisionManagerViewPeopleFedJPanel", supervisionManagerViewPeopleFedJPanel);

        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.next(mainPanel);

    }//GEN-LAST:event_btnPeopleFedActionPerformed

    private void btnWastageAvoidedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWastageAvoidedActionPerformed

        SupervisionManagerViewWastageAvoidedBySupplierJPanel supervisionManagerViewWastageAvoidedBySupplier = new SupervisionManagerViewWastageAvoidedBySupplierJPanel(mainPanel, network);
        mainPanel.add("SupervisionManagerViewWastageAvoidedBySupplier", supervisionManagerViewWastageAvoidedBySupplier);
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.next(mainPanel);
    }//GEN-LAST:event_btnWastageAvoidedActionPerformed

    private void btnWastageAvoidedChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWastageAvoidedChartActionPerformed
        // TODO add your handling code here:
        SupervisionManagerViewChartJPanel supervisionManagerViewChart = new SupervisionManagerViewChartJPanel(mainPanel, network);
        mainPanel.add("SupervisionManagerViewChart", supervisionManagerViewChart);
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.next(mainPanel);
    }//GEN-LAST:event_btnWastageAvoidedChartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPeopleFed;
    private javax.swing.JButton btnWastageAvoided;
    private javax.swing.JButton btnWastageAvoidedChart;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblValue;
    // End of variables declaration//GEN-END:variables

}
